name: tflite_image_classification
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  flutter_custom_cards: ^0.2.1
  carousel_pro: ^1.0.0
  shimmer_animation: ^2.1.0
  easy_localization: ^3.0.1
  flutter_launcher_icons: ^0.11.0
  network_info_plus: ^3.0.1
  iconly: ^1.0.1
  lottie: ^1.4.3
  smooth_page_indicator: ^1.0.0+2
  google_fonts: ^3.0.1
  get: ^4.6.5
  
  tflite: ^1.1.2
  image_picker: ^0.8.4+11
flutter_icons: 
  android : true
  image_path: "assets/cannbis.png"    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lang/
    - assets/images/
    - assets/icons/
 


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
